dist: "bionic"
language: "python"
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
script:
  - pipenv run safety check
  - pipenv run black . --check
  - pipenv run python -m pytest
