dist: "bionic"
language: "python"
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --pre
  # remove --pre when black gets around to releasing v1.0
script:
  - pipenv run safety check
  - pipenv run black . --check
  - pipenv run python -m pytest
